services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "password123!"
    ports:
      - "1433:1433"

  api:
    image: web_api
    container_name: web_api_application
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DB_SA_PASSWORD=password123!
      - ConnectionStrings__sqlConnection=Server=db;User Id=sa;Password=password123!;Database=Learn;TrustServerCertificate=True;
      - USE_DOCKER=true

    ports:
      - "5000:80"
    depends_on:
      - db
